defaults:
  - _self_
device: cuda
gpu_id: 0
seed: 42
action_expert_adaptive_mode:
quantize: False
lora: False
lora_r: 32
lora_dropout: 0.0
pretrained_model_path: ${oc.env:DRIVEMOE_REPO_DIR}/ckpts/paligemma-3b-pt-224
checkpoint_path: "YOUR_CHECKPOINT_PATH"  # You need to set path

data:
  statistics_path: ${oc.env:REPO_DIR}/config/statistics/b2d_statistics.json

flow_sampling: beta
num_inference_steps: 10
final_action_clip_value: 1.0
debug: False
save_images: False

cond_steps: 5
horizon_steps: 10
action_dim: 2
proprio_dim: 10
max_seq_len: 532
tokenizer_padding: max_length # instead of truncating to longest
max_image_text_tokens: ${max_seq_len}

mixture:
  vlm:   # gemma
    hidden_size: 2048
    intermediate_size: 16384
    use_final_norm: False
    cache: True
    use_quantize: ${quantize}
    use_lora: ${lora}
    adaptive_mode:  # not applicable for gemma
  proprio:
    hidden_size: 1024
    intermediate_size: 4096
    use_final_norm: True  # technically no, but sharing weights with action anyway
    cache: True
    use_quantize: False
    use_lora: False
    adaptive_mode: ${action_expert_adaptive_mode}
  action:
    hidden_size: 1024
    intermediate_size: 4096
    use_final_norm: True
    cache: False
    use_quantize: False
    use_lora: False
    adaptive_mode: ${action_expert_adaptive_mode}
time_hidden_size: 256 # only applicable if using adaptive

# Fixed
image_token_index: 257152
vocab_size: 257216
pad_token_id: 0

vision:
  _target_: src.model.paligemma.siglip.SiglipVisionModel
  config:
    hidden_size: 1152 # siglip
    intermediate_size: 4304
    num_hidden_layers: 27
    num_attention_heads: 16
    num_channels: 3
    image_size: 224
    patch_size: 14
    layer_norm_eps: 1e-6
    attention_dropout: 0.0
    num_image_tokens: 512 # 2 images: 256 * 2
    lora:
      r: ${lora_r}
      dropout: ${lora_dropout}
  use_quantize: ${quantize}
  use_lora: ${lora}

vision_projector:
  _target_: src.model.paligemma.siglip.PaliGemmaMultiModalProjector
  config:
    vision_config:
      hidden_size: 1152
      projection_dim: 2048
    lora:
      r: ${lora_r}
      dropout: ${lora_dropout}
  use_quantize: ${quantize}
  use_lora: ${lora}

joint:
  _target_: src.model.DrivePi0.joint_model.JointModel
  config:
    action_expert_adaptive_mode: ${action_expert_adaptive_mode}
    time_hidden_size: ${time_hidden_size}
    mixture: ${mixture}
    lora:
      r: ${lora_r}
      dropout: ${lora_dropout}
    num_hidden_layers: 18
    num_attention_heads: 8
    num_key_value_heads: 1
    head_dim: 256
    max_position_embeddings: 8192
    rms_norm_eps: 1e-6
    rope_theta: 10000.0
    attention_bias: False
    attention_dropout: 0.0
    pad_token_id: ${pad_token_id}